### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by vgeruso** [andrelmlins/freesoccer#10]
Good Morning, me and [rosoareslv](https://github.com/rosoareslv) are members of a team from the Paradigmas of Software Development discipline of the Catholic University of Salvador (Ucsal), Salvador city state of Bahia from Brazil and we are doing work to contribute to an open source project and to complete the text we're doing about freesoccer, we have the following questions:

1 - What is the purpose of the project?
2 - Do you have any form of project monetization?
3 - Do you have any sponsorship?

**Comment by andrelmlins** [comment]
1 - The aim of this project is to provide free football data and expand web scraping technique.
2 - Not
3 - Not

**Comment by vgeruso** [comment]
very well, thanks!
