### ISSUE TITLE
Create URL documentation

### ISSUE THREAD

**Issue by vgeruso** [andrelmlins/freesoccer#11]
In this api, a clear documentation of each url could be created, showing its request method, input and output of each, for better understanding of the system users.

Exemple: 

## resultes of brazilian championship series A
url: http://localhost:4000/scraping/cbf/:competition/results

### Parameters: 
 - /scraping -> represents data scraping
- /cbf -> is the federation of the championship
- /:competition -> is the code of the championship -> example: `campeonato-brasileiro-serie-a`
- /results -> says the API wants the championship results

**Comment by andrelmlins** [comment]
In this JSON file we have all the api documentation for swagger. We may publish this documentation again. https://github.com/andrelmlins/freesoccer/blob/master/src/config/swagger.json

**Comment by vgeruso** [comment]
ok
